/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Rdma */

#ifndef _Included_Rdma
#define _Included_Rdma
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Rdma
 * Method:    start_server
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Rdma_start_1server
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     Rdma
 * Method:    stop_server
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Rdma_stop_1server
  (JNIEnv *, jobject);

/*
 * Class:     Rdma
 * Method:    connect_to_server
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Rdma_connect_1to_1server
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Rdma
 * Method:    send_binary_nonblock
 * Signature: (J[BJI)I
 */
JNIEXPORT jint JNICALL Java_Rdma_send_1binary_1nonblock
  (JNIEnv *, jobject, jlong, jbyteArray, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
